#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-paranamer
Version  : cb6709646eed97c271d73f50ad750cc43c8e052a
Release  : 2
URL      : https://github.com/paul-hammant/paranamer/archive/cb6709646eed97c271d73f50ad750cc43c8e052a/paranamer-cb6709646eed97c271d73f50ad750cc43c8e052a.tar.gz
Source0  : https://github.com/paul-hammant/paranamer/archive/cb6709646eed97c271d73f50ad750cc43c8e052a/paranamer-cb6709646eed97c271d73f50ad750cc43c8e052a.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jdk-paranamer-data
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-apache-parent
BuildRequires : jdk-aqute-bndlib
BuildRequires : jdk-atinject
BuildRequires : jdk-cdi-api
BuildRequires : jdk-cglib
BuildRequires : jdk-commons-beanutils
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-digester
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-validator
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-eclipse-eclipse
BuildRequires : jdk-eclipse-osgi
BuildRequires : jdk-eclipse-osgi-services
BuildRequires : jdk-felix
BuildRequires : jdk-felix-bundlerepository
BuildRequires : jdk-felix-framework
BuildRequires : jdk-felix-osgi-foundation
BuildRequires : jdk-felix-utils
BuildRequires : jdk-glassfish-servlet-api
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-hamcrest
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-jtidy
BuildRequires : jdk-junit4
BuildRequires : jdk-kxml
BuildRequires : jdk-log4j
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-bundle-plugin
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-dependency-tree
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-impl
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-mockito
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-objenesis
BuildRequires : jdk-osgi-compendium
BuildRequires : jdk-osgi-core
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-qdox
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy-java
BuildRequires : jdk-sonatype-oss-parent
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn

%description
# ![ParaNamer](http://paulhammant.com/images/ParaNamer.jpg)
## Method Parameter Name Access for Java*

%package data
Summary: data components for the jdk-paranamer package.
Group: Data

%description data
data components for the jdk-paranamer package.


%prep
%setup -q -n paranamer-cb6709646eed97c271d73f50ad750cc43c8e052a

find -name "*.class" -print -delete
find -name "*.jar" -print ! -name "test.jar" -delete
python3 /usr/share/java-utils/pom_editor.py pom_xpath_remove   "pom:build/pom:extensions"
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  -r :maven-dependency-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  -r :maven-javadoc-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  -r :maven-source-plugin
python3 /usr/share/java-utils/pom_editor.py pom_disable_module paranamer-distribution
python3 /usr/share/java-utils/pom_editor.py pom_remove_dep -r net.sourceforge.f2j:
python3 /usr/share/java-utils/pom_editor.py pom_xpath_remove   -r "pom:dependency[pom:classifier = 'javadoc' ]"
rm -r paranamer/src/test/com/thoughtworks/paranamer/JavadocParanamerTest.java
rm -r paranamer/src/test/com/thoughtworks/paranamer/BytecodeReadingParanamerTestCase.java

%build
python3 /usr/share/java-utils/mvn_build.py -s

%install
xmvn-install  -R .xmvn-reactor -n paranamer -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/paranamer/paranamer-ant.jar
/usr/share/java/paranamer/paranamer-generator.jar
/usr/share/java/paranamer/paranamer-it-011.jar
/usr/share/java/paranamer/paranamer-maven-plugin.jar
/usr/share/java/paranamer/paranamer.jar
/usr/share/maven-metadata/paranamer-paranamer-ant.xml
/usr/share/maven-metadata/paranamer-paranamer-generator.xml
/usr/share/maven-metadata/paranamer-paranamer-integration-tests.xml
/usr/share/maven-metadata/paranamer-paranamer-it-011.xml
/usr/share/maven-metadata/paranamer-paranamer-maven-plugin.xml
/usr/share/maven-metadata/paranamer-paranamer-parent.xml
/usr/share/maven-metadata/paranamer-paranamer.xml
/usr/share/maven-poms/paranamer/paranamer-ant.pom
/usr/share/maven-poms/paranamer/paranamer-generator.pom
/usr/share/maven-poms/paranamer/paranamer-integration-tests.pom
/usr/share/maven-poms/paranamer/paranamer-it-011.pom
/usr/share/maven-poms/paranamer/paranamer-maven-plugin.pom
/usr/share/maven-poms/paranamer/paranamer-parent.pom
/usr/share/maven-poms/paranamer/paranamer.pom
